{% set version = '0.5.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-packrat
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/packrat_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/packrat/packrat_{{ version }}.tar.gz
  sha256: d6a09290fbe037a6c740921c5dcd70b500e5b36e4713eae4010adf0c456bc5f7

build:
  merge_build_host: True  # [win]
  number: 1001
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('packrat')"           # [not win]
    - "\"%R%\" -e \"library('packrat')\""  # [win]

about:
  home: https://github.com/rstudio/packrat/
  license: GPL-2
  summary: Manage the R packages your project depends on in an isolated, portable, and reproducible
    way.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: packrat
# Type: Package
# Title: A Dependency Management System for Projects and their R Package Dependencies
# Version: 0.5.0
# Author: Kevin Ushey, Jonathan McPherson, Joe Cheng, Aron Atkins, JJ Allaire
# Maintainer: Kevin Ushey <kevin@rstudio.com>
# Description: Manage the R packages your project depends on in an isolated, portable, and reproducible way.
# License: GPL-2
# Depends: R (>= 3.0.0)
# Imports: tools, utils
# Suggests: testthat (>= 0.7), devtools, httr, knitr, rmarkdown
# URL: https://github.com/rstudio/packrat/
# BugReports: https://github.com/rstudio/packrat/issues
# RoxygenNote: 6.1.1
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2018-11-13 23:16:36 UTC; kevin
# Repository: CRAN
# Date/Publication: 2018-11-14 08:40:02 UTC
