appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: gy7hDtsyoc2TUe1FDF7YWuJmQ/wP0u+VpblvBqaZlCzQaatM8wejlXh/dk+jV2Z/3dun0hzeNRtwjX4JDLaGNqZXLxSeeCMZAJQEgr5f4H5/iiM53ZE4nGpYgtw6zuEPJfVhPEDy+er9qi9iJeRKeNc5eyRFNz+Yww0pDmFJ/Gt6anJ8iiWqjwULK5v8kQKXF7P5rHSlSL+16wMJL8dJGrtKfLnIh4jZTw9Do2Ft7TPyym48yHTO3sPSoa0qK+5Or43Kw9WUPG7JFxaPY2KZyVei0P1M51qZGsjxR+LgYpmw0QovppsjW/29YyCnzW2uZYT9OX8fBuyPC32asYhforjDpEp7e24hhlD5QqP55Aytaf2mDM31COXZ2gIjCqY74+pcpv9WAY7LeYmo3Q3D//MqXijsp0iikIbT6tbKn7sba958aBSsvEQs6XOW/y2YO3mlE4xwL1a3r+1rZ3z/i0ZNZY+isVbt+4/ZP+z36dBsFA8UnQWzGqv0CHVJI/jWyz7feH+vjeqJyHSpYp56ZDfNid82UE0i0ClPz3LHiJrzfFzaIaz7DcCTzgEDoPtJ7Q8Rtjp7sh0pf7zyLJmDVxDMdcdz9eErpZS/hTdpjICrCIoJXOyev9MRh3U0avwTmJ5YAIkAjpaBtlgHNeaCJ5FeB6vwc5WVDqkd0epYuyc=
conda_forge_output_validation: true
